### ISSUE TITLE
Add support for cl_khr_device_uuid

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CLHPP#111]
@bashbaug highlighted we don't have support in the 2020/09/01 teleconference.

**Comment by bashbaug** [comment]
I added support for cl_khr_device_uuid with https://github.com/KhronosGroup/OpenCL-CLHPP/pull/135.  I think we can close this one?

**Comment by bashbaug** [comment]
Closing - fixed by #135.  Thanks!
