### ISSUE TITLE
CL_PROFILING_COMMAND_COMPLETE not supported

### ISSUE THREAD

**Issue by jasonsewall-intel** [KhronosGroup/OpenCL-CLHPP#114]
OpenCL 2.2 has a cl_profiling_info enum that opencl.hpp doesn't appear to support: CL_PROFLING_COMMAND_COMPLETE.

See table 33: https://www.khronos.org/registry/OpenCL/specs/2.2/html/OpenCL_API.html#event-objects.

I think this should be supported.

**Comment by kpet** [comment]
I've created https://github.com/KhronosGroup/OpenCL-CLHPP/issues/114 that should fix this. I notice we have no tests for event profiling functions. We should definitely add some.
