### ISSUE TITLE
Add CI coverage for older versions of OpenCL

### ISSUE THREAD

**Issue by jrprice** [KhronosGroup/OpenCL-CLHPP#133]
Would potentially help catch issues such as the one fixed by https://github.com/KhronosGroup/OpenCL-CLHPP/pull/130

**Comment by bashbaug** [comment]
We don't test OpenCL 1.0 or 1.1, but we currently have CI coverage for all versions of OpenCL 1.2 and newer.  I think we can close this issue.

**Comment by bashbaug** [comment]
Closing, we test back to OpenCL 1.2 now, which should catch most issues.  Let's revisit if we find we really need to go all the way back to OpenCL 1.1 or 1.0.  Thanks!
