### ISSUE TITLE
Question: why xxx_svm_vector use int as the default type of SVMAllocator

### ISSUE THREAD

**Issue by YOUSIKI** [KhronosGroup/OpenCL-CLHPP#143]
I'm a newbie for CLHPP, and I'm wondering why `int` is used as the default value type of SVMAllocator for svm_vectors (such as coarse_svm_vector). As shown in the following snippet (Line 3873 of `include/CL/opencl.hpp`).

```cpp
template < class T >
using coarse_svm_vector = vector<T, cl::SVMAllocator<int, cl::SVMTraitCoarse<>>>;
```

Won't this cause fault when I'm trying to use other value types, such as float64 or struct. 

Thanks for your help in advance.

**Comment by Greatpanc** [comment]
template<class T >
using cl::coarse_svm_vector = typedef vector<T, cl::SVMAllocator<int, cl::SVMTraitCoarse<>>>
Vector alias to simplify contruction of coarse-grained SVM containers.
