### ISSUE TITLE
Update example code

### ISSUE THREAD

**Issue by ODON1** [KhronosGroup/OpenCL-CLHPP#149]
As novice open-cl-clhpp user i was delighted to see the example code highlighting usage etc.. As this is from the official open-cl-clhpp and in the source code i hoped it would be showing idiomatic usage and be up-to-date. 

However it took me some effort and frustration to get it working. In order to give other new users a better experience i would propose the following changes.

1) Have the program check for open_cl version >= 200
I ran the program on my Intel i5-8400 with integrated GPU which reports itself as Platform Version OpenCL 3.0. So it refused to run as this is not opencl 2.0

2) Mention (or have the program check for) minimum compile options -pthread -lOpenCL
This may be obvious to most of you, but I never thought of compiling with -pthread. On my system this gave very uninformative 'system error' and just quit. (turned out makedefault uses std::runonce which needs threads)

3) The program tries to read an output2 which was never defined
Probably original code wanted to show reading from SVM and device memory but one got removed.
This was easy but still i think the code should run without needing to sort this out and fixing it.

As to what the program showcases and how is a matter of opinion. To me it was very useful as is. I do have some questions though
 - shouldn't there be an "if(get_global_id(0)==0)" in kernel2 before enqueuing the new commands? Now all 16 workers will enqueue a kernel that writes to the third and last quarter of the array. So these values each get written 16 times.
 - Following on the previous point: why doesn't this lead to problems (accessing the same array value from multiple workers)? I tried using printf() statements to follow but they all come out in (ascending work-item) order.

Link to the doxygen page with example code
[http://github.khronos.org/OpenCL-CLHPP/](url)

**Comment by bashbaug** [comment]
Thanks for filing this issue and apologies for the frustration!

We'll get this updated.

I'm intrigued by (2) especially.  Can you please send a little more information about your system - what Linux distro you're using and what compiler you're compiling with?  If you can send the exact command you use to compile that would be most useful.

Thanks again!

**Comment by ODON1** [comment]
Here's some runs from my system.
Let me know if you'd like more info.

```
❯ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsute

❯ clang++ OpenCLCPPexampleOrig.cpp  -lOpenCL -o OpenCLCPPexampleOrig.out

❯ ./OpenCLCPPexampleOrig.out
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
[1]    17175 IOT instruction (core dumped)  ./OpenCLCPPexampleOrig.out

❯ g++ OpenCLCPPexampleOrig.cpp -lOpenCL -o OpenCLCPPexampleOrig.out

❯ ./OpenCLCPPexampleOrig.out
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
[1]    17201 IOT instruction (core dumped)  ./OpenCLCPPexampleOrig.out

❯ clang++ OpenCLCPPexampleOrig.cpp  -lOpenCL -pthread -o OpenCLCPPexampleOrig.out

❯ ./OpenCLCPPexampleOrig.out
Output:
        0: 11
        1: 11
        2: 11
        3: 11
        4: 11
        5: 11
        6: 11
        7: 11
        8: 11
        9: 11
        10: 11
        11: 11
        12: 11
        13: 11
        14: 11
        15: 11
        16: 78
        17: 78
        18: 78
        19: 78
        20: 78
        21: 78
        22: 78
        23: 78
        24: 80
        25: 80
        26: 80
        27: 80
        28: 80
        29: 80
        30: 80
        31: 80


❯ g++ OpenCLCPPexampleOrig.cpp -lOpenCL -pthread -o OpenCLCPPexampleOrig.out

❯ ./OpenCLCPPexampleOrig.out
Output:
        0: 11
        1: 11
        2: 11
        3: 11
        4: 11
        5: 11
        6: 11
        7: 11
        8: 11
        9: 11
        10: 11
        11: 11
        12: 11
        13: 11
        14: 11
        15: 11
        16: 78
        17: 78
        18: 78
        19: 78
        20: 78
        21: 78
        22: 78
        23: 78
        24: 80
        25: 80
        26: 80
        27: 80
        28: 80
        29: 80
        30: 80
        31: 80
```

**Comment by bashbaug** [comment]
Thanks!  I created a PR to update the example that I think should fix this issue.

I added a note about compiling with `-pthread` also.  For reference:

https://stackoverflow.com/questions/51584960/stdcall-once-throws-stdsystem-error-unknown-error-1
