### ISSUE TITLE
New stable release soon?

### ISSUE THREAD

**Issue by ghisvail** [KhronosGroup/OpenCL-CLHPP#16]
Following the discussion started in [here](https://github.com/clMathLibraries/clSPARSE/issues/162), we were wondering whether a new stable release of `clhpp` was planned soon (2.0.10?), which would include the includes this fix (https://github.com/KhronosGroup/OpenCL-CLHPP/commit/befe77b66fd3dd87ce9fef940e475cdc71d8bd9f) in particular. This way, Linux distributions such as Debian could target the packaging on this specific stable release, rather than take an arbitrary snapshot.

Thanks,
Ghis

**Comment by jrprice** [comment]
I agree we are due a new release that incorporates the latest bug fixes. I will look into getting this done in the near future.

**Comment by ghisvail** [comment]
:+1:

**Comment by jrprice** [comment]
We have now published `v2.0.10` of `cl2.hpp` that incorporates all of the latest changes:

https://github.com/KhronosGroup/OpenCL-CLHPP/releases
