### ISSUE TITLE
Support Conan package

### ISSUE THREAD

**Issue by FTamas77** [KhronosGroup/OpenCL-CLHPP#171]
I'm new here and probably this is not the best place to ask it. I'd like to use OpenCL.
I read [here](https://www.khronos.org/opencl/) about the C++ API. Is this official package I can use instead of C API?
I added this my conan file:
khronos-opencl-clhpp/20191105@bincrafters/stable
but it does not work. I found the conan package here: [Conan](https://conan.io/center/khronos-opencl-clhpp)
The latest version is two years old. How frequently does it updated/released?
I'd like to use the C++ API and I read C++ kernel code is also supported (maybe since 2.0v of OpenCL(?)).
I'm not sure whether I should install it from here (this repo) or I can be free to use Conan package.
Sorry, but SYCL and OpenCL is a little bit still confusing however I saw some very good figures and read the history.

**Comment by MathiasMagnus** [comment]
@FTamas77 Unfortunately I have little knowledge of Conan, but as you can see the latest tagged version is [2.0.15](https://github.com/KhronosGroup/OpenCL-CLHPP/tree/v2.0.15) which is from 2021/06/22, which is much newer than the latest Conan 2019/11/05. It seems that the Conan maintainer of that package hasn't touched it in a while. We are happy if somebody picks up maintenance of that package, as package manager support is certainly welcome. I myself am a contributor to multiple Vcpkg ports in the OpenCL ecosystem and those are in fairly good shape. I do intend on updating all packages the OpenCL package in Vcpkg once the base change sets to the OpenCL-SDK samples are merged across the ecosystem.

**Comment by ilya-lavrenov** [comment]
PR https://github.com/conan-io/conan-center-index/pull/17416

**Comment by ilya-lavrenov** [comment]
can be closed as done.

**Comment by bashbaug** [comment]
Closing as suggested above - thank you!
