### ISSUE TITLE
A curious name collision bug

### ISSUE THREAD

**Issue by ZackhamGuo** [KhronosGroup/OpenCL-CLHPP#197]
```
#include <CL/opencl.hpp>
int main(){}
```
This code will compile. However, this:
```
#include <CL/opencl.hpp>
int end = 0; //Which is a variable I have purpose to use. Name this varaible as begin cause same error.
int main(){}
```
Cannot compile. This is the most curious bug I have ever encountered. It gives VS C2064 "term does not evaluate to a function taking 1 arguments", and "prev": cannot find indentifier.

As I know, compiler process source file line by line and follows look-up rule. Anything happen below SHOULD not interfere things before. I am very curios that declaring a variable of my own can make a header file producing error. I would be very happy if anyone can explain how such thing could happen. As for the error it does not matter anymore. I have many ways to settle it.

More spefically, this line is 1110, something like this:
```
param->assign(begin(value), prev(end(value)));
```
Where it use something named `end()`, but this is nothing special, just using some `std::string` utilities `begin()` `end()`. Why this specific header error such thing? header `cl.hpp` also use such but it does not generate error with my own variable in global namespace `begin` or `end`.

**Comment by keryell** [comment]
Nice catch!
On line 1110 t`begin()` and `end()` are found by ADL to `std::begin()` and `std::end()` which breaks when a user-defined `begin` and `end` does exist. :-(
The OpenCL header should use `std::begin()` and `std::end()` instead.

**Comment by keryell** [comment]
Same bug with `std::prev`. We need to look more carefully at this old code... :-(

**Comment by keryell** [comment]
Actually there is a `clang-tidy` improvement in review for these problems https://reviews.llvm.org/D72282 but it is not merged yet.

**Comment by bashbaug** [comment]
Would it be OK to call std::begin() and std::end() explicitly or would that potentially break `CL_HPP_NO_STD_VECTOR`?

One alternative we could consider is to call the `begin()` and `end()` member functions instead.  Getting rid of `prev` is a little harder, but maybe something like this would work?

```c++
param->assign(value.begin(), --value.end());
```

**Comment by keryell** [comment]
What is the problem with using `std::prev()` too?

**Comment by bashbaug** [comment]
> What is the problem with using `std::prev()` too?

If I understand correctly the idea behind using `cl::vector` and not `std::vector` is that it enables an application to provide its own vector class.  Have a look at [CL_HPP_NO_STD_VECTOR](https://github.com/KhronosGroup/OpenCL-CLHPP/blob/0772def7d0f1deb27c9138d4b6904d472893afe0/include/CL/opencl.hpp#L153).  I think this means we shouldn't use any `std::` functions with a `cl::vector`?  It's possible I'm misunderstanding how this should work...

**Comment by keryell** [comment]
C++ is way better than C. :-) Just try.
In https://en.cppreference.com/w/cpp/iterator/begin you can see all the ways `std::begin` can find the right information for you. I assume that a user-provided container will provide the `begin()` and `end()` member functions which will be used by `std::begin` and `std::end`.

**Comment by bashbaug** [comment]
Nice, I think this will work with `begin` and `end` then.  Will it work with `prev`?  That one is likely to be the most tricky.

https://en.cppreference.com/w/cpp/iterator/prev

Regarding my previous suggestion, I see at this link:

> Although the expression `--c.end()` often compiles, it is not guaranteed to do so: `c.end()` is an rvalue expression, and there is no iterator requirement that specifies that decrement of an rvalue is guaranteed to work.

Hrm.
