### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bkmgit** [KhronosGroup/OpenCL-CLHPP#20]
Is it possible to indicate licensing in readme? Assume some open source license since there are forks and variations, eg. https://github.com/9prady9/OpenCL-CLHPP.git

**Comment by jrprice** [comment]
The license is included at the top of the header file itself, but we could probably add a `LICENSE.txt` to the root of the repository as well if that makes things even clearer.

**Comment by bkmgit** [comment]
Adding a LICENSE.txt would be great, thanks.
