### ISSUE TITLE
Build cl.hpp for releases, not just cl2.hpp

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/OpenCL-CLHPP#25]
Could the release builds be extended to include generating the old cl.hpp as well? That would let me remove it from the OpenCL registry, where it's the only header file still stored there instead of in github.

**Comment by jrprice** [comment]
Personally I'd like to get rid of the old `cl.hpp` completely, given that the new `cl2.hpp` supports all the 1.x versions of OpenCL as well and has many other general improvements. That would mean that the registry could just point users to `cl2.hpp` for all versions of OpenCL.

I'll see if I can get agreement to do this from the working group.

**Comment by oddhack** [comment]
That would be even better. I didn't realize cl2.hpp was usable for CL 1.x (largely because the name suggests otherwise :-) )

**Comment by jrprice** [comment]
I agree, the name may be misleading here. It's not backwards compatible with the previous version which is why there was a name change when adding the 2.0 support. We may want to consider another name change if we want to present this as a 'one size fits all' header.

**Comment by kpet** [comment]
I think a name change is indeed the way to go. The current state is pretty confusing and it wouldn't be hard to keep backwards compatibility with applications using `cl2.hpp`. `opencl.hpp`? Any other suggestions?

**Comment by rajhlinux** [comment]
I was getting compiler errors and never knew that cl2.hpp is the replacement and updated header file for cl.hpp

So many github projects like "Caffe" (Deep learning framework) and many others have not updated to cl2.hpp and getting this error on 2022... At least this thread clear things up.

**Comment by bashbaug** [comment]
Would it be helpful to describe this more explicitly in the README?  It currently describes cl2.hpp (and how it has been renamed to opencl.hpp), but there is currently no description for cl.hpp.

It would be nice to add more clarification to the Doxygen docs also, though it is at least mentioned [there](http://khronosgroup.github.io/OpenCL-CLHPP/):

> There are numerous compatibility, portability and memory management fixes in the new header as well as additional OpenCL 2.0 features. As a result the header is not directly backward compatible and for this reason we release it as [opencl.hpp](https://github.khronos.org/OpenCL-CLHPP/opencl_8hpp.html) rather than a new version of cl.hpp.
