### ISSUE TITLE
New MSVC warning in `cl::copy`

### ISSUE THREAD

**Issue by MathiasMagnus** [KhronosGroup/OpenCL-CLHPP#293]
Previously MSVC threw a warning for using naked pointers with algorithms in Debug builds without using a vendor utility promising that the pointers are valid over a certain range. Latest VS deprecated this feature and now it issues a deprecation warning.

```
D:\Develop\GPGPU1\build\msbuild-msvc\_deps\opencl-sdk-src\external\OpenCL-CLHPP\include\CL\opencl.hpp(10031,50): warning C4996: 'stdext::checked_array_iterator<DataType *>::checked_array_iterator': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning. [D:\Develop\GPGPU1\build\msbuild-msvc\OpenCL\C++-API\SAXPY\OpenCL-Cpp-SAXPY.vcxproj]
```

**Comment by Kerilk** [comment]
This is breaking the CI:
Here are the offending code lines:
https://github.com/KhronosGroup/OpenCL-CLHPP/blob/6db44b8db11952b53d271b6d1657ac5d04a45871/include/CL/opencl.hpp#L10302-L10310

**Comment by bashbaug** [comment]
https://github.com/KhronosGroup/OpenCL-CLHPP/pull/309 might fix this issue.

I don't have easy access to all versions of visual studio to test, but this at least "fixes" our CI failures.

**Comment by bashbaug** [comment]
#309 fixes this issue.  Closing.
