### ISSUE TITLE
Errors with cl2.hpp

### ISSUE THREAD

**Issue by sampie** [KhronosGroup/OpenCL-CLHPP#35]
Hi,

Using cl2.hpp results to compile error. The system is Ubuntu 16.04 and has following related packages (nvidia-384, nvidia-opencl-dev, nvidia-opencl-icd-384). What could be wrong?

/tmp/ccG4wJ8n.o: In function `cl::detail::ReferenceHandler<_cl_device_id*>::release(_cl_device_id*)':
dummy.cpp:(.text._ZN2cl6detail16ReferenceHandlerIP13_cl_device_idE7releaseES3_[_ZN2cl6detail16ReferenceHandlerIP13_cl_device_idE7releaseES3_]+0x14): undefined reference to `clReleaseDevice'
/tmp/ccG4wJ8n.o: In function `cl::detail::ReferenceHandler<_cl_context*>::release(_cl_context*)':
dummy.cpp:(.text._ZN2cl6detail16ReferenceHandlerIP11_cl_contextE7releaseES3_[_ZN2cl6detail16ReferenceHandlerIP11_cl_contextE7releaseES3_]+0x14): undefined reference to `clReleaseContext'
/tmp/ccG4wJ8n.o: In function `cl::detail::ReferenceHandler<_cl_command_queue*>::release(_cl_command_queue*)':
dummy.cpp:(.text._ZN2cl6detail16ReferenceHandlerIP17_cl_command_queueE7releaseES3_[_ZN2cl6detail16ReferenceHandlerIP17_cl_command_queueE7releaseES3_]+0x14): undefined reference to `clReleaseCommandQueue'
collect2: error: ld returned 1 exit status

--- compile command --
g++ -std=c++17 -lOpenCL dummy.cpp -o dummy

--- dummy.cpp --
#define CL_HPP_ENABLE_EXCEPTIONS
#define CL_HPP_TARGET_OPENCL_VERSION 200

#include "cl2.hpp"

int main(int argc, char** argv)
{
  return 0;
}

**Comment by sampie** [comment]
I also tested with different system having beignet and the result looks the same:

/tmp/ccEVrV8e.o: In function `cl::detail::ReferenceHandler<_cl_device_id*>::release(_cl_device_id*)':
dummy.cpp:(.text._ZN2cl6detail16ReferenceHandlerIP13_cl_device_idE7releaseES3_[_ZN2cl6detail16ReferenceHandlerIP13_cl_device_idE7releaseES3_]+0x14): undefined reference to `clReleaseDevice'
/tmp/ccEVrV8e.o: In function `cl::detail::ReferenceHandler<_cl_context*>::release(_cl_context*)':
dummy.cpp:(.text._ZN2cl6detail16ReferenceHandlerIP11_cl_contextE7releaseES3_[_ZN2cl6detail16ReferenceHandlerIP11_cl_contextE7releaseES3_]+0x14): undefined reference to `clReleaseContext'
/tmp/ccEVrV8e.o: In function `cl::detail::ReferenceHandler<_cl_command_queue*>::release(_cl_command_queue*)':
dummy.cpp:(.text._ZN2cl6detail16ReferenceHandlerIP17_cl_command_queueE7releaseES3_[_ZN2cl6detail16ReferenceHandlerIP17_cl_command_queueE7releaseES3_]+0x14): undefined reference to `clReleaseCommandQueue'
collect2: error: ld returned 1 exit status
Makefile:2: recipe for target 'all' failed

**Comment by jrprice** [comment]
Linker flag order matters with GCC, try putting the `-lOpenCL` at the end of the command-line:

    g++ -std=c++17 dummy.cpp -o dummy -lOpenCL

This resolves the issue for me.

**Comment by sampie** [comment]
Hi,

Thank you! This solves the issue!

**Comment by rajhlinux** [comment]
Thanks I had the same issue to compile Caffe. I had to put the flag "-lOpenCL" to the cmakelist.txt flags.
