### ISSUE TITLE
Kernel Functor not compiling?

### ISSUE THREAD

**Issue by soulslicer** [KhronosGroup/OpenCL-CLHPP#38]
A basic example like this does not seem to compile. Why is this the case?

```
cl::Buffer buffer; // assume to be allocated
cl::KernelFunctor<cl::Buffer> kf = cl::KernelFunctor<cl::Buffer>(resizeAndMergeKernel);
kf.setArgs(buffer);
```
```
error: no matching function for call to ‘cl::KernelFunctor<cl::Buffer>::setArgs(cl::Buffer&)’
                             kf.setArgs(buffer);
```

**Comment by soulslicer** [comment]
My bad:

`kf(cl::EnqueueArgs(cl::NDRange(1,1)), buffer);`

**Comment by soulslicer** [comment]
is constructing a kernel functor expensive? assuming i pass in a reference of cl::Kernel everytime

**Comment by jrprice** [comment]
Sorry missed this question.

Looking at the implementation, constructing a kernel functor should be cheap, since it just holds a kernel object. It just provides the convenience of being able to use `operator()`.
