### ISSUE TITLE
CMake Install Destination is Wrong

### ISSUE THREAD

**Issue by jonathonl** [KhronosGroup/OpenCL-CLHPP#41]
The line at https://github.com/KhronosGroup/OpenCL-CLHPP/blob/master/include/CMakeLists.txt#L18 should be `DESTINATION include`.

Currently, the CL directory is installed into the install prefix base, e.g., '/usr/local' instead of '/usr/local/include'.

**Comment by dakcarto** [comment]
This certainly needs merged, yes? This change was necessary for me to ensure the bindings could even be found and used.
