### ISSUE TITLE
cl2.hpp throwing errors when compiling project on Linux

### ISSUE THREAD

**Issue by CaptainHorse** [KhronosGroup/OpenCL-CLHPP#42]
I'm trying to compile my project that's using cl2.hpp on Linux (Ubuntu 16.04), it throws a lot of errors. 

Here are some of them:
```
cl2.hpp:6606:5: error: expected identifier before numeric constant
     None = 0,

cl2.hpp:6606:5: error: expected ‘}’ before numeric constant

cl2.hpp:6611:8: error: ‘QueueProperties’ does not name a type; did you mean ‘XSetWMProperties’?
 inline QueueProperties operator|(QueueProperties lhs, QueueProperties rhs)

cl2.hpp:8230:51: error: invalid use of incomplete type ‘class CommandQueue’
 CL_HPP_DEFINE_STATIC_MEMBER_ cl_int CommandQueue::default_error_ = CL_SUCCESS;

cl2.hpp:9366:54: error: ‘NDRange’ has not been declared
     EnqueueArgs(CommandQueue &queue, NDRange offset, NDRange global, NDRange local)
```

**Comment by jrprice** [comment]
Are those the very first errors you get?

Which OpenCL headers are you compiling against / where did you get the from? It looks a bit like you might be compiling against headers that do not have the OpenCL 2.0 functions/definitions in them.

**Comment by CaptainKrisu** [comment]
I copied the master a month or so back, since the release version was out of date by years.

I'm including cl2.hpp, but using OpenCL 1.2 since my machine is not capable of higher, and other reasons.

I use AMD APP SDK 3.0 for the SDK's

**Comment by Saeid7r** [comment]
I had the same problem defining CL_HPP_TARGET_OPENCL_VERSION and CL_HPP_MINIMUM_OPENCL_VERSION to value 120 just before including cl2.hpp removed the errors

#define CL_HPP_TARGET_OPENCL_VERSION 120
#define CL_HPP_MINIMUM_OPENCL_VERSION 120
#include <CL/cl2.hpp>

I think that should fix your problem at least partialy

**Comment by Saeid7r** [comment]
I had the same problem so defined below macros before including cl2.hpp.
#define CL_HPP_TARGET_OPENCL_VERSION 120
#define CL_HPP_MINIMUM_OPENCL_VERSION 120
#include <CL/cl2.hpp>
These will make the errors go away since it makes parts of code that need higher opencl version get omitted.
If you replace 120 with your version of opencl perhaps it this would help you too.

**Comment by jrprice** [comment]
@CaptainHorse Can you confirm whether the above suggestion resolves your issue?

**Comment by CaptainHorse** [comment]
@jrprice No, I've had these preprocessor defines in the code ever since I started working on OpenCL compute.
```c++
#define CL_HPP_ENABLE_EXCEPTIONS
#define CL_HPP_MINIMUM_OPENCL_VERSION 120
#define CL_HPP_TARGET_OPENCL_VERSION 120
#include <cl2.hpp>
```

I haven't touched OpenCL on Linux for a long time, I'll have to set a new VM up since I deleted last one due to issues with it. Will post a follow up comment as I get it going.

**Comment by CaptainHorse** [comment]
No longer an issue, I did use Fedora 29 instead of Ubuntu 16.04 this time though.
