### ISSUE TITLE
isReferenceCountable(cl_device_id device) unused variable warning

### ISSUE THREAD

**Issue by LeMoussel** [KhronosGroup/OpenCL-CLHPP#44]
When compiling with this parameters `-Wall -Wextra -std=c++11 -O2 -Os -s -DNDEBUG`, I got 

> 
> cl2.hpp: In static member function 'static bool cl::detail::Wrapper<_cl_device_id*>::isReferenceCountable(cl_device_id)':
> cl2.hpp:1740:51: warning: unused parameter 'device' [-Wunused-parameter]
>      static bool isReferenceCountable(cl_device_id device)

**Comment by bashbaug** [comment]
This was fixed by https://github.com/KhronosGroup/OpenCL-CLHPP/pull/168.  Closing!
