### ISSUE TITLE
cl2.hpp/cl.hpp  does not work for OpenCL 1.1

### ISSUE THREAD

**Issue by gallickgunner** [KhronosGroup/OpenCL-CLHPP#48]
So according to the `cl2.hpp`

> C++ bindings for OpenCL 1.0 (rev 48), OpenCL 1.1 (rev 33),  OpenCL 1.2 (rev 15) and OpenCL 2.0 (rev 29)

However when I tried targeting my project for openCL 1.1 using these defines
```
#define CL_MINIMUM_OPENCL_VERSION 110
#define CL_HPP_MINIMUM_OPENCL_VERSION 110
#define CL_HPP_TARGET_OPENCL_VERSION 110
#define CL_TARGET_OPENCL_VERSION 110
```
It throws a bunch of errors shown below. The errors remain the same if i use `cl.hpp`

![errors](https://user-images.githubusercontent.com/40718428/42260767-1915f2fa-7f7f-11e8-9e15-26f8d22e95b9.png)

The project compiles fine if I change the last two defines to `1.2.0` or greater. I have tried both, using the precompiled release version which gives `cl2.hpp` and compiling the `cl2.hpp` myself using cmake.

Any help would be appreciated.

Additional Information.
OS: Win 7 64-bit
IDE: Codeblocks
Compiler : Mingw-w64 gcc 8.1.0 (32- bit version)  Have also tried (mingw32 gcc 6.3.0)
GPU: Radeon hd 7950 (OpenCL 2.0 supported)

**Comment by jrprice** [comment]
Fixed now that #49 is merged.
