### ISSUE TITLE
VkCpp bindings? 

### ISSUE THREAD

**Issue by acterhd** [KhronosGroup/OpenCL-CLHPP#5]
Hello? Have you plan to create vulkan hpp bindings? 
I very want C++ bindings for Vulkan API, not only OpenCL. 
Please, make! 

For opengl already have boosty oglplus (oglplu2).

**Comment by jrprice** [comment]
NVIDIA have produced some C++ bindings for Vulkan:
https://github.com/nvpro-pipeline/vkcpp
