### ISSUE TITLE
linking error with mingw

### ISSUE THREAD

**Issue by Diskein** [KhronosGroup/OpenCL-CLHPP#50]
Macro CL_HPP_DEFINE_STATIC_MEMBER_ is defined as __attribute__((weak)) on linux, and as __declspec__(selectany) on windows. It is not work for mingw.

**Comment by kpet** [comment]
Thanks for the report. Could you create a PR with your proposed fix please?

**Comment by Diskein** [comment]
Yes, I could create fix
