### ISSUE TITLE
CL_HPP_MINIMUM/TARGET_OPENCL_VERSION is not forwarded

### ISSUE THREAD

**Issue by gcp** [KhronosGroup/OpenCL-CLHPP#53]
The OpenCL headers were switched to a unified build: https://github.com/KhronosGroup/OpenCL-Headers/commit/de26592167b9fdea503885e40e8755393c56523d

Which now expects CL_TARGET_OPENCL_VERSION to be set.

If CL_HPP_TARGET_OPENCL_VERSION is set, then this is not forwarded to the above configuration variable, so the code will start to produce warnings which can only be fixed by defining both. That's a rather ugly kludge.

**Comment by jrprice** [comment]
Fixed - thanks for the bug report!
