### ISSUE TITLE
Please add specialization cl::Program::build(cl::Device&)

### ISSUE THREAD

**Issue by sirzooro** [KhronosGroup/OpenCL-CLHPP#60]
It is possible to create `cl::Context` using `cl::Device` instead of `std::vector<cl::Device>`, so it would be nice to use `cl::Program::build` in the same way.

BTW, this special constructor of `cl::Context` is not documented in opencl-cplusplus-1.2.pdf, please add it there.

**Comment by kpet** [comment]
Thanks for the report, this seems like a good idea.

**Comment by kpet** [comment]
Adding the agenda label to discuss the process around opencl-cplusplus-1.2.pdf.

**Comment by bashbaug** [comment]
I just created #102 to add the requested build interface - thank you for the suggestion!

Regarding the PDF documentation, after discussing in the working group teleconference I have created https://github.com/KhronosGroup/OpenCL-Registry/pull/83, which removes the PDF documentation from the registry webpage.  As you have observed, the PDFs have grown stale and out of date.  Instead, we recommend referring to the Doxygen documentation, which is easier to keep up-to-date.

Please also feel free to track #65, which will automatically generate and publish Doxygen comments when the headers change.
