### ISSUE TITLE
undefined behaviour in tests/test_cl2hpp.cpp

### ISSUE THREAD

**Issue by DiscreteLogarithm** [KhronosGroup/OpenCL-CLHPP#86]
The `clGetKernelSubGroupInfo_testSubGroups` in `tests/test_cl2hpp.cpp` is defined with a return type of `cl_int`, but does not return any value which is an undefined behaviour. It should either be declared `void` or return some value.

**Comment by bashbaug** [comment]
Just FYI, I fixed this already in PR #83. 

Just need someone to review it and get it merged - ping @kpet or @jrprice ? :smile:

**Comment by DiscreteLogarithm** [comment]
@bashbaug  Thanks for your comment. This is actually different from PR #83 . This bug is in `tests/test_cl2hpp.cpp` and it is the `clGetKernelSubGroupInfo_testSubGroups` function that should be changed.

**Comment by bashbaug** [comment]
Whoops, typo, I meant #82, not #83.
