### ISSUE TITLE
More precise template parameter type for Platform::getInfo<>()

### ISSUE THREAD

**Issue by TSlivede** [KhronosGroup/OpenCL-CLHPP#92]
Couldn't the declaration
```
    template <cl_int name> typename
    detail::param_traits<detail::cl_platform_info, name>::param_type
    getInfo(cl_int* err = NULL) const
```
at [Line 2466 of `cl2.hpp`](https://github.com/KhronosGroup/OpenCL-CLHPP/blob/master/include/CL/cl2.hpp#L2466) be changed without braking compatibility to this?
```
    template <cl_platform_info name> typename
    detail::param_traits<detail::cl_platform_info, name>::param_type
    getInfo(cl_int* err = NULL) const
```
(changing the template parameter type of `name`)

This way it would be much more obvious what kind of values can be accepted as the template parameter.

**Comment by TSlivede** [comment]
The same applies to [cl_device_info](https://github.com/KhronosGroup/OpenCL-CLHPP/blob/387174808abd743f869da345ccad6282b9fc845d/include/CL/cl2.hpp#L2180), [cl_context_info](https://github.com/KhronosGroup/OpenCL-CLHPP/blob/387174808abd743f869da345ccad6282b9fc845d/include/CL/cl2.hpp#L3023), [cl_event_info](https://github.com/KhronosGroup/OpenCL-CLHPP/blob/387174808abd743f869da345ccad6282b9fc845d/include/CL/cl2.hpp#L3165), [cl_profiling_info](https://github.com/KhronosGroup/OpenCL-CLHPP/blob/387174808abd743f869da345ccad6282b9fc845d/include/CL/cl2.hpp#L3188), [cl_mem_info](https://github.com/KhronosGroup/OpenCL-CLHPP/blob/387174808abd743f869da345ccad6282b9fc845d/include/CL/cl2.hpp#L3380), and so on.

Just search for `template <cl_int name>` in [cl2.hpp](https://github.com/KhronosGroup/OpenCL-CLHPP/blob/master/include/CL/cl2.hpp). In all 18 occurrences, the template parameter type can be changed from `cl_int` to a more precise type. All those methods just forward `name` to another method as a (regular, non template) argument that has that more precise type.

**Comment by bashbaug** [comment]
> This way it would be much more obvious what kind of values can be accepted as the template parameter.

This makes sense to me.  @jprice, any idea why the these functions currently use `cl_int` as the template parameter?  This issue affects both the old cl.hpp and the new cl2.hpp.

**Comment by jrprice** [comment]
> any idea why the these functions currently use cl_int as the template parameter?

No, that history predates my involvement with this header. I can't think of any reason not to do this.
