### ISSUE TITLE
Warning C26439 when compiling in Visual Studio 2019

### ISSUE THREAD

**Issue by TSlivede** [KhronosGroup/OpenCL-CLHPP#93]
When using `cl2.hpp` in Visual Studio 2019 I'm getting a lot of [C26439](https://docs.microsoft.com/en-us/cpp/code-quality/c26439) IntelliSense Warnings ("This kind of function may not throw. Declare it 'noexcept'.").

The problem seems to be, that at [Line 532](https://github.com/KhronosGroup/OpenCL-CLHPP/blob/master/include/CL/cl2.hpp#L532) it is not detected, that `nothrow` is supported, because Visual Studio doesn't set `__cplusplus` to an up to date value by default. (Only if [`/Zc:__cplusplus`](https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus) comandline option is given.)
```
#if (__cplusplus >= 201103L)
#define CL_HPP_NOEXCEPT_ noexcept
#else
#define CL_HPP_NOEXCEPT_
#endif
```

Could Line 532 be changed to this?
```
#if (__cplusplus >= 201103L || _MSVC_LANG >= 201103L )
```

If `_MSVC_LANG` is not defined it will be evaluated as 0. ([section 16.1 paragraph 4: "After all replacements due to macro expansion and the defined unary operator have been performed, all remaining identifiers and keywords, except for true and false, are replaced with the pp-number 0"](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2012/n3337.pdf#page=403)) If it is defined, than [it's at least Visual Studio 2015 Update 3](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros), which is AFAIK does support `noexcept` (["noexcept operator was introduced and is supported in Visual Studio 2015"](https://github.com/MicrosoftDocs/cpp-docs/blob/8bc0a0e703fd454c42a70965d548708fe503a44b/docs/cpp/exception-specifications-throw-cpp.md)).

__&lt;Edit>__
`noexcept` was added in the [November 2013 CTP (customer technology preview) of the Visual C++ Compiler](https://devblogs.microsoft.com/cppblog/announcing-the-visual-c-compiler-november-2013-ctp/).
__&lt;/Edit>__

This doesn't seem to remove all C26439 warnings but at least more than half of them.

__&lt;Edit2>__
Note: Although exception specifications in Visual C++ are [only completely standard conform if `/std:c++17` is used](https://devblogs.microsoft.com/oldnewthing/20180928-00/?p=99855), it is not necessary to test for `_MSVC_LANG >= 201703L`, because the behavior of `noexcept` is standard conform even without `/std:c++17`.
__&lt;/Edit2>__

**Comment by bashbaug** [comment]
Huh, that's annoying, but this does appear to be done on purpose.  From https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=vs-2019:

> Because lots of existing code appears to depend on the value of this macro matching "199711L", the compiler does not change the value of the macro unless you explicitly opt-in by using the /Zc:__cplusplus compiler option. 

The recommend resolution is to check `_MSVC_LANG` as suggested above.

Are you able to create a PR with this change?  If not, I'll take care of this tomorrow.  Thanks!

**Comment by TSlivede** [comment]
@bashbaug 

>Are you able to create a PR with this change?

[Done](https://github.com/KhronosGroup/OpenCL-CLHPP/pull/94)
